csatlakozz oldal
simonyiszk/mabe pull request #133
Opened 2021-11-27 23:15 UTC by perryd01

2021-11-27 23:21 UTC, NoszDom requested changes
A főoldalon lévő csatlakozás gomb is mutasson erre az oldalra, vagy a formra

2021-11-28 11:34 UTC, OmTheTurtle commented on src/utils/contentful.ts
> +import {
```suggestion
import type {
```

Enélkül failel a build.

2021-11-28 11:38 UTC, OmTheTurtle commented on src/pages/csatlakozz/index.tsx
> +					<div className="relative z-30 py-8 px-4 lg:px-16 mx-auto max-w-xs sm:max-w-2xl bg-white rounded-mainPage shadow-mainPageCards cursor-pointer">
Miért kell ide a `relative z-30`?

2021-11-28 12:58 UTC, NoszDom approved these changes

2021-11-28 12:59 UTC, merged